language: php

sudo: false

php:
  - 7
  - 7.1
  - 7.2
  - nightly

env: TMPDIR=/tmp

branches:
  only:
    master

install:
  - phpenv rehash
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer phpstan

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
